# Generated by Django 6.0.3 on 2026-04-01 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_courses_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courses',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courses',
            name='url',
            field=models.URLField(default='NA'),
        ),
        migrations.AlterUniqueTogether(
            name='courses',
            unique_together={('created_by', 'url')},
        ),
        migrations.AddField(
            model_name='courses',
            name='tags',
            field=models.ManyToManyField(related_name='courses', to='tracker.tag'),
        ),
    ]
