# Generated by Django 6.0.3 on 2026-04-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_studysessions_duration_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysessions',
            name='duration_min',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studysessions',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
