# Generated by Django 6.0.3 on 2026-04-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('instructor', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('no_modules', models.IntegerField()),
            ],
        ),
    ]
