# Generated by Django 6.0.3 on 2026-04-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='url',
            field=models.URLField(default='NA', unique=True),
        ),
    ]
