# Generated by Django 6.0.3 on 2026-04-01 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_tag_courses_created_by_courses_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
