# Generated by Django 6.0.3 on 2026-04-02 05:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_courses_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysessions',
            name='duration_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studysessions',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
