# Generated by Django 6.0.3 on 2026-04-02 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_studysessions_duration_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streaks',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL),
        ),
    ]
